namespace AppDeCadastroDeAnimes
{
	public enum Genero
	{
		Acao = 1,
		Demonios = 2,
		Harem = 3,
		Criancas = 4,
		Musica = 5,
		Romance = 6,
		Shoujo = 7,
		Espaço = 8,
		Vampiro = 9,
		Aventura = 10,
		Drama = 11,
		Hentai = 12,
		Magia = 13,
        Misterio = 14,
        Samurai = 15,
        Shoujo_Ai = 16,
        Esportes = 17,
        Yaoi = 18,
        Carros = 19,
        Ecchi = 20,
        Historico = 21,
        Artes_Marciais = 22,
        Parodia = 23,
        Escola = 24,
        Shounen = 25,
        Yuri = 26,
        Comedia = 27,
        Fantasia = 28,
        Horror = 29,
        Meca = 30,
        Sci_fi = 31,
        Shounen_Ai = 32,
        Sobrenatural = 33,
        Josei = 34,
        Psicologico = 35
	}
}